name: cachcach
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  path: any
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  get: ^4.3.8
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1
  flutter_spinkit: ^5.1.0
  freezed: ^0.15.0+1
  intl: ^0.17.0
  floor: ^1.2.0
  permission_handler: ^8.2.5
  flutter_native_splash: ^2.1.6
  firebase_messaging: 10.0.9
  firebase_core: 1.8.0
  flutter_local_notifications: 9.2.0
  image_picker: ^0.8.4+3
  shared_preferences: 2.0.8
  flutter_svg: 1.0.0
  file_picker: 4.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Black.otf
        - asset: fonts/NotoSansJP-Bold.otf
        - asset: fonts/NotoSansJP-Light.otf
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Regular.otf
        - asset: fonts/NotoSansJP-Thin.otf
